project:
  type: default
  output-dir: _site
  execute-dir: project
  render:
    - index.qmd

format:
  html:
    toc: true
    toc-depth: 2
    link-external-newwindow: true
    fig-responsive: true
    embed-resources: false

execute:
  message: false
  warning: false
  error: false
